---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imageshift-selfsigned-issuer
  namespace: sandbox
spec:
  isCA: true
  commonName: imageshift-selfsigned-issuer
  secretName: imageshift-selifsigned-root
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imageshift
  namespace: sandbox
spec:
  secretName: imageshift-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - cert-manager
  commonName: wcrum.dev
  dnsNames:
    - imageshift-webhook.sandbox.svc
  emailAddresses:
    - will@wcrum.dev
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: imageshift-selfsigned-issuer
  namespace: sandbox
spec: {}