{{if .Values.tls.selfSigned}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: imageshift-selfsigned-issuer
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imageshift-webook-serving-cert
  namespace: {{.Values.namespace}}
spec:
  dnsNames:
  - imageshift-webhook-service.imageshift.svc
  - imageshift-webhook-service.imageshift.svc.cluster.local
  secretName: {{.Values.tls.secretName}}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: imageshift-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{end}}