apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imageshift-init-mwc-access
  namespace: {{.Values.namespace}}
subjects:
- kind: ServiceAccount
  name: imageshift-init-sa
  namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole 
  name: imageshift-init-mwc-role
  apiGroup: rbac.authorization.k8s.io