apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageshift-init-mwc-role
  namespace: {{.Values.namespace}}
rules:
- apiGroups: ["admissionregistration.k8s.io", ""]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "update", "patch", "delete", "list"] 