apiVersion: v1
kind: Service
metadata:
  name: imageshift-webhook-service
  namespace: {{.Values.namespace}}
  labels:
    app: imageshift-webhook
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: imageshift-webhook